apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassini
  namespace: mercury
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: cassini
  template:
    metadata:
      labels:
        app: cassini
    spec:
      containers:
        - name: app
          image: nginx:1.31-alpine
          env:
            - name: APP_VERSION
              value: "2"
          ports:
            - containerPort: 80
