apiVersion: v1
kind: Namespace
metadata:
  name: aspen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-new-c32
  namespace: aspen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-new-c32
  template:
    metadata:
      labels:
        app: api-new-c32
    spec:
      containers:
        - name: api
          image: nginx:1.31-alpine
          readinessProbe:
            httpGet:
              path: /missing
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 3
